version: '3.9'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev-phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
